apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy
  template:
    metadata:
      labels:
        app: dummy
    spec:
      containers:
      - name: khangpham2712-dummy
        image: khangpham2712/dummy:latest
        resources:
          limits:
            memory: "2Gi"
            cpu: "1000m"
        ports:
        - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: dummy-service
spec:
  selector:
    app: dummy
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051